import {
  bigint,
  boolean,
  char,
  index,
  int,
  json,
  longtext,
  mysqlEnum,
  mysqlTable,
  primaryKey,
  smallint,
  tinyint,
  text,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/mysql-core';
import { coordinate, createdAt, id, money, timestamp, updatedAt } from '../columns.js';
import { users } from './users.js';

export const healthTipCategories = mysqlTable(
  'health_tip_categories',
  {
    id: id('id').primaryKey(),
    name: varchar('name', { length: 128 }).notNull(),
    /** URL segment on the public blog (/blog/category/{slug}). */
    slug: varchar('slug', { length: 160 }),
    description: text('description'),
    image: varchar('image', { length: 1024 }),
    metaTitle: varchar('meta_title', { length: 160 }),
    metaDescription: varchar('meta_description', { length: 320 }),
    sortOrder: int('sort_order').notNull().default(0),
  },
  (t) => [uniqueIndex('health_tip_categories_slug_uq').on(t.slug)],
);

/** Bylines for blog posts: writers and the clinicians who medically review them. */
export const blogAuthors = mysqlTable(
  'blog_authors',
  {
    id: id('id').primaryKey(),
    name: varchar('name', { length: 128 }).notNull(),
    slug: varchar('slug', { length: 160 }).notNull(),
    /** Credentials shown next to the name, e.g. "MBBS, General Practitioner". */
    jobTitle: varchar('job_title', { length: 160 }),
    bio: text('bio'),
    image: varchar('image', { length: 1024 }),
    /** Profile URLs (LinkedIn, practice page...) emitted as schema.org `sameAs`. */
    links: json('links').$type<string[]>().notNull().default([]),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('blog_authors_slug_uq').on(t.slug)],
);

export const BLOG_POST_STATUSES = ['draft', 'published'] as const;
export type BlogPostStatus = (typeof BLOG_POST_STATUSES)[number];

/**
 * Health tips double as the public blog: the patient app and the website read
 * the same rows. A post is live when status = published and published_at has
 * passed; a future published_at schedules it.
 */
export const healthTips = mysqlTable(
  'health_tips',
  {
    id: id('id').primaryKey(),
    categoryId: id('category_id').references(() => healthTipCategories.id, { onDelete: 'set null' }),
    authorId: id('author_id').references(() => blogAuthors.id, { onDelete: 'set null' }),
    reviewerId: id('reviewer_id').references(() => blogAuthors.id, { onDelete: 'set null' }),
    title: varchar('title', { length: 255 }).notNull(),
    slug: varchar('slug', { length: 255 }),
    excerpt: varchar('excerpt', { length: 500 }),
    /** HTML body. */
    description: longtext('description').notNull(),
    image: varchar('image', { length: 1024 }),
    imageAlt: varchar('image_alt', { length: 255 }),
    type: varchar('type', { length: 32 }).notNull().default('article'),
    status: mysqlEnum('status', BLOG_POST_STATUSES).notNull().default('draft'),
    featured: boolean('featured').notNull().default(false),
    tags: json('tags').$type<string[]>().notNull().default([]),
    readingMinutes: int('reading_minutes').notNull().default(1),
    metaTitle: varchar('meta_title', { length: 160 }),
    metaDescription: varchar('meta_description', { length: 320 }),
    focusKeyword: varchar('focus_keyword', { length: 120 }),
    canonicalUrl: varchar('canonical_url', { length: 1024 }),
    noindex: boolean('noindex').notNull().default(false),
    views: int('views').notNull().default(0),
    isSent: boolean('is_sent').notNull().default(false),
    publishedAt: timestamp('published_at'),
    reviewedAt: timestamp('reviewed_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('health_tips_category_published_idx').on(t.categoryId, t.publishedAt),
    index('health_tips_status_published_idx').on(t.status, t.publishedAt),
    index('health_tips_author_idx').on(t.authorId),
    uniqueIndex('health_tips_slug_uq').on(t.slug),
  ],
);

export const healthTipViews = mysqlTable(
  'health_tip_views',
  {
    healthTipId: id('health_tip_id')
      .notNull()
      .references(() => healthTips.id, { onDelete: 'cascade' }),
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.healthTipId, t.userId] })],
);

/**
 * One row per article view on the public website (anonymous visitors). No IP address is stored:
 * `visitorHash` is a SHA-256 of the IP, user agent and a salt that changes daily, so a visitor can
 * be counted once per day but never identified or followed across days.
 */
export const blogPostViews = mysqlTable(
  'blog_post_views',
  {
    id: bigint('id', { mode: 'number', unsigned: true }).autoincrement().primaryKey(),
    postId: id('post_id')
      .notNull()
      .references(() => healthTips.id, { onDelete: 'cascade' }),
    /** Random id generated by the page, used to attach the engagement beacon to this view. */
    viewId: char('view_id', { length: 36 }).notNull(),
    visitorHash: char('visitor_hash', { length: 64 }).notNull(),
    /** ISO 3166-1 alpha-2, or null when the location is unknown (e.g. local or private IPs). */
    country: char('country', { length: 2 }),
    region: varchar('region', { length: 100 }),
    city: varchar('city', { length: 100 }),
    /** Where the visit came from: a referring host ("google.com"), a utm_source, or null for direct. */
    source: varchar('source', { length: 120 }),
    device: mysqlEnum('device', ['mobile', 'tablet', 'desktop']).notNull(),
    /** Seconds the page was visible, reported when the reader leaves. Null until reported. */
    engagedSeconds: smallint('engaged_seconds', { unsigned: true }),
    /** Furthest point of the article reached, 0–100. */
    scrollDepth: tinyint('scroll_depth', { unsigned: true }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('blog_post_views_view_uq').on(t.viewId),
    index('blog_post_views_post_created_idx').on(t.postId, t.createdAt),
    index('blog_post_views_created_idx').on(t.createdAt),
  ],
);

export const healthTipLikes = mysqlTable(
  'health_tip_likes',
  {
    healthTipId: id('health_tip_id')
      .notNull()
      .references(() => healthTips.id, { onDelete: 'cascade' }),
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.healthTipId, t.userId] })],
);

export const anonymousQuestions = mysqlTable(
  'anonymous_questions',
  {
    id: id('id').primaryKey(),
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    question: text('question').notNull(),
    answer: text('answer'),
    status: mysqlEnum('status', ['pending', 'completed']).notNull().default('pending'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('anonymous_questions_user_idx').on(t.userId, t.createdAt)],
);

export const NOTIFICATION_TYPES = [
  'chat',
  'transaction',
  'appointment',
  'medication',
  'call',
  'lab_result',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPES)[number];

export const notifications = mysqlTable(
  'notifications',
  {
    id: id('id').primaryKey(),
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: mysqlEnum('type', NOTIFICATION_TYPES).notNull(),
    title: varchar('title', { length: 512 }).notNull(),
    uniqueId: varchar('unique_id', { length: 128 }),
    status: mysqlEnum('status', ['delivered', 'read']).notNull().default('delivered'),
    createdAt: createdAt(),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.status, t.createdAt)],
);

export const referrals = mysqlTable(
  'referrals',
  {
    id: id('id').primaryKey(),
    /** The referred (new) user. A user can only be referred once. */
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Referrer's tag as entered at sign-up. */
    referrerTag: varchar('referrer_tag', { length: 64 }).notNull(),
    referrerId: id('referrer_id').references(() => users.id, { onDelete: 'set null' }),
    status: mysqlEnum('status', ['active', 'inactive']).notNull().default('active'),
    signupBonusPaid: boolean('signup_bonus_paid').notNull().default(false),
    totalCommissionEarned: money('total_commission_earned').notNull().default(0),
    lastCommissionAt: timestamp('last_commission_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('referrals_user_uq').on(t.userId),
    index('referrals_referrer_idx').on(t.referrerTag, t.createdAt),
  ],
);

export const waitlistEntries = mysqlTable(
  'waitlist_entries',
  {
    id: id('id').primaryKey(),
    userId: id('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    address: varchar('address', { length: 512 }).notNull(),
    latitude: coordinate('latitude').notNull(),
    longitude: coordinate('longitude').notNull(),
    createdAt: createdAt(),
  },
  (t) => [index('waitlist_entries_user_idx').on(t.userId)],
);
